name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  release:
    name: release
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/steps/step-release.yaml
  merge:
    needs: release
    name: merge
    permissions:
      contents: write
    uses: ./.github/workflows/steps/step-merge.yaml